# -*- coding: utf-8 -*-
"""resume_shortlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7o6MOYpvx8jZbTC0wZYIZ7qyP-VIDUl
"""

!pip install -q pdfplumber spacy scikit-learn pandas matplotlib seaborn
!python -m spacy download en_core_web_md -q

print("All libraries installed!")

# Cell 2: Import all libraries
import pdfplumber
import spacy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os
from google.colab import files
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

# Load spaCy model
nlp = spacy.load("en_core_web_md")

print("All imports done!")

# Cell 3: Upload your PDF resumes (select multiple at once)

print("Upload your PDF resumes (you can select multiple files):")
uploaded = files.upload()

resume_files = [f for f in uploaded.keys() if f.endswith('.pdf')]
print(f"\n{len(resume_files)} resume(s) uploaded:")
for f in resume_files:
    print(f"   📄 {f}")

# Cell 4: Extract text from each uploaded PDF resume

def extract_text_from_pdf(filepath):
    """Extract clean text from a PDF file using pdfplumber."""
    text = ""
    with pdfplumber.open(filepath) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + " "
    text = re.sub(r'\s+', ' ', text).strip()
    return text

resumes = {}
print("📃 Extracting text from resumes...\n")
for filename in resume_files:
    text = extract_text_from_pdf(filename)
    name = filename.replace('.pdf', '')
    resumes[name] = text
    print(f"  {name}: {len(text.split())} words extracted")

print(f"\nAll {len(resumes)} resumes extracted!")

# Cell 5: Paste your job description here

job_description = """
We are looking for a skilled Data Scientist with experience in Python,
machine learning, deep learning, and data analysis. The candidate should
have hands-on experience with TensorFlow or PyTorch, scikit-learn, pandas,
and NumPy. Strong knowledge of NLP, computer vision, and statistical modeling
is required. Experience with SQL, data visualization (Matplotlib, Seaborn,
Tableau), and cloud platforms (AWS, GCP) is a plus. A degree in Computer
Science, Statistics, or a related field is preferred.
Required Skills: Python, Machine Learning, Deep Learning, NLP, SQL,
TensorFlow, PyTorch, scikit-learn, Data Visualization, Statistics.
"""

# Replace the text above with your actual job description

print("📋 Job Description loaded!")
print(f"   Word count: {len(job_description.split())}")
print(f"\n--- Preview ---\n{job_description[:300]}...")

# Cell 6: Model 1 - TF-IDF Cosine Similarity Scoring

def clean_text(text):
    """Lowercase, remove special characters."""
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Clean all texts
jd_clean      = clean_text(job_description)
resume_names  = list(resumes.keys())
resume_texts  = [clean_text(t) for t in resumes.values()]

# TF-IDF vectorizer
tfidf    = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))
all_docs = [jd_clean] + resume_texts
tfidf_matrix = tfidf.fit_transform(all_docs)

# Cosine similarity between JD (index 0) and each resume
jd_vector      = tfidf_matrix[0]
resume_vectors = tfidf_matrix[1:]
tfidf_scores   = cosine_similarity(jd_vector, resume_vectors)[0]

# Build results dataframe
tfidf_results = pd.DataFrame({
    'Candidate'   : resume_names,
    'TFIDF_Score' : np.round(tfidf_scores * 100, 2)
}).sort_values('TFIDF_Score', ascending=False).reset_index(drop=True)
tfidf_results.index += 1
tfidf_results['TFIDF_Rank'] = tfidf_results.index

print("=" * 45)
print("  Model 1: TF-IDF Cosine Similarity Ranking")
print("=" * 45)
display(tfidf_results[['TFIDF_Rank', 'Candidate', 'TFIDF_Score']].rename(
    columns={'TFIDF_Score': 'Match Score (%)'}))

# Cell 7: Model 2 - spaCy NLP Semantic Similarity + Skill Matching

# Common tech skill keywords to look for
SKILL_KEYWORDS = [
    "python", "java", "sql", "machine learning", "deep learning", "nlp",
    "tensorflow", "pytorch", "keras", "scikit-learn", "pandas", "numpy",
    "data analysis", "statistics", "computer vision", "aws", "gcp", "azure",
    "docker", "git", "tableau", "power bi", "r", "spark", "hadoop",
    "data visualization", "neural network", "regression", "classification"
]

def extract_skills(text):
    """Extract matched skill keywords from text."""
    text_lower = text.lower()
    return set(skill for skill in SKILL_KEYWORDS if skill in text_lower)

def spacy_score(jd_text, resume_text):
    """Compute spaCy semantic similarity + skill overlap score."""
    # Semantic similarity via spaCy word vectors
    jd_doc     = nlp(jd_text[:10000])   # spaCy has token limit
    res_doc    = nlp(resume_text[:10000])
    semantic   = jd_doc.similarity(res_doc)

    # Skill overlap score
    jd_skills  = extract_skills(jd_text)
    res_skills = extract_skills(resume_text)
    if len(jd_skills) == 0:
        skill_score = 0
    else:
        matched     = jd_skills & res_skills
        skill_score = len(matched) / len(jd_skills)

    # Weighted combination: 50% semantic + 50% skill match
    final = (0.5 * semantic) + (0.5 * skill_score)
    return round(final * 100, 2), round(semantic * 100, 2), round(skill_score * 100, 2)

print("Running spaCy NLP scoring...\n")
spacy_data = []
for name, text in resumes.items():
    final, semantic, skill = spacy_score(job_description, text)
    jd_skills  = extract_skills(job_description)
    res_skills = extract_skills(text)
    matched    = jd_skills & res_skills
    missing    = jd_skills - res_skills
    spacy_data.append({
        'Candidate'       : name,
        'NLP_Score'       : final,
        'Semantic_Score'  : semantic,
        'Skill_Score'     : skill,
        'Skills_Matched'  : len(matched),
        'Skills_Missing'  : len(missing),
        'Matched_Skills'  : ', '.join(sorted(matched)) or 'None',
        'Missing_Skills'  : ', '.join(sorted(missing)) or 'None'
    })

spacy_results = pd.DataFrame(spacy_data).sort_values(
    'NLP_Score', ascending=False).reset_index(drop=True)
spacy_results.index += 1
spacy_results['NLP_Rank'] = spacy_results.index

print("=" * 45)
print("  Model 2: spaCy NLP + Skill Match Ranking")
print("=" * 45)
display(spacy_results[['NLP_Rank', 'Candidate', 'NLP_Score',
                        'Semantic_Score', 'Skill_Score',
                        'Skills_Matched', 'Matched_Skills']].rename(columns={
    'NLP_Score'      : 'Final Score (%)',
    'Semantic_Score' : 'Semantic (%)',
    'Skill_Score'    : 'Skill Match (%)'
}))

# Cell 8: Merge both results and compare

merged = tfidf_results[['Candidate', 'TFIDF_Score', 'TFIDF_Rank']].merge(
         spacy_results[['Candidate', 'NLP_Score', 'NLP_Rank',
                         'Matched_Skills', 'Missing_Skills']],
         on='Candidate')

merged['Avg_Score'] = ((merged['TFIDF_Score'] + merged['NLP_Score']) / 2).round(2)
merged = merged.sort_values('Avg_Score', ascending=False).reset_index(drop=True)
merged.index += 1
merged['Final_Rank'] = merged.index

print("=" * 60)
print("      FINAL COMBINED RANKING — BOTH MODELS")
print("=" * 60)
display(merged[['Final_Rank', 'Candidate', 'TFIDF_Score',
                 'NLP_Score', 'Avg_Score', 'Matched_Skills']].rename(columns={
    'TFIDF_Score' : 'TF-IDF (%)',
    'NLP_Score'   : 'NLP (%)',
    'Avg_Score'   : 'Avg Score (%)'
}))

# Cell 9: Visualize the results

candidates = merged['Candidate'].tolist()
x = np.arange(len(candidates))
width = 0.3

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Resume Shortlisting — Model Comparison', fontsize=16, fontweight='bold')

# Plot 1: Side-by-side bar chart
ax1 = axes[0, 0]
ax1.bar(x - width/2, merged['TFIDF_Score'], width, label='TF-IDF', color='steelblue',  edgecolor='black')
ax1.bar(x + width/2, merged['NLP_Score'],   width, label='NLP',    color='mediumseagreen', edgecolor='black')
ax1.set_xticks(x)
ax1.set_xticklabels(candidates, rotation=20, ha='right')
ax1.set_title('TF-IDF vs NLP Score per Candidate')
ax1.set_ylabel('Score (%)')
ax1.legend()
ax1.set_ylim(0, 100)

# Plot 2: Average score ranking
ax2 = axes[0, 1]
colors = ['gold', 'silver', '#cd7f32'] + ['steelblue'] * (len(candidates) - 3)
bars = ax2.barh(merged['Candidate'][::-1], merged['Avg_Score'][::-1],
                color=colors[::-1], edgecolor='black')
ax2.set_title('Final Ranking by Average Score')
ax2.set_xlabel('Average Score (%)')
ax2.set_xlim(0, 100)
for bar, score in zip(bars, merged['Avg_Score'][::-1]):
    ax2.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
             f'{score}%', va='center', fontweight='bold')

# Plot 3: Skill match count
ax3 = axes[1, 0]
ax3.bar(candidates, merged['Matched_Skills'].apply(
    lambda x: len(x.split(',')) if x != 'None' else 0),
    color='salmon', edgecolor='black')
ax3.set_title('Number of Skills Matched per Candidate')
ax3.set_ylabel('Skills Matched')
ax3.set_xticklabels(candidates, rotation=20, ha='right')

# Plot 4: Scatter - TF-IDF vs NLP scores
ax4 = axes[1, 1]
scatter = ax4.scatter(merged['TFIDF_Score'], merged['NLP_Score'],
                      s=150, c=merged['Avg_Score'],
                      cmap='RdYlGn', edgecolors='black', zorder=5)
for _, row in merged.iterrows():
    ax4.annotate(row['Candidate'],
                 (row['TFIDF_Score'], row['NLP_Score']),
                 textcoords="offset points", xytext=(6, 4), fontsize=8)
ax4.set_xlabel('TF-IDF Score (%)')
ax4.set_ylabel('NLP Score (%)')
ax4.set_title('TF-IDF vs NLP — Scatter Plot')
plt.colorbar(scatter, ax=ax4, label='Avg Score')

plt.tight_layout()
plt.savefig('resume_shortlisting_results.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Chart saved as resume_shortlisting_results.png")

"""# New Section"""

# Cell 10: Print final shortlist report

threshold = 40   # Adjust this cutoff score as needed

print("=" * 60)
print("         RESUME SHORTLISTING FINAL REPORT")
print("=" * 60)
print(f"\nJob Role   : Data Scientist")
print(f"Resumes    : {len(resumes)}")
print(f"Threshold  : {threshold}% avg score to be shortlisted\n")

shortlisted = merged[merged['Avg_Score'] >= threshold]
rejected    = merged[merged['Avg_Score'] <  threshold]

print(f"SHORTLISTED ({len(shortlisted)} candidate(s)):")
print("-" * 60)
for _, row in shortlisted.iterrows():
    print(f"   Rank #{int(row['Final_Rank'])}  |  {row['Candidate']}")
    print(f"       TF-IDF: {row['TFIDF_Score']}%  |  NLP: {row['NLP_Score']}%  |  Avg: {row['Avg_Score']}%")
    print(f"       ✔ Skills: {row['Matched_Skills']}")
    print(f"       ✘ Missing: {row['Missing_Skills']}\n")

print(f" NOT SHORTLISTED ({len(rejected)} candidate(s)):")
print("-" * 60)
for _, row in rejected.iterrows():
    print(f"  {row['Candidate']} — Avg Score: {row['Avg_Score']}%")

print("\n" + "=" * 60)
print(" Shortlisting complete!")